# CI de Nível 01

name: 'Execução Manual - n1'

# Triggers

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3

    - name: Instalando dependências
      run: npm i

    - name: Instalando Yarn
      run: npm install -g yarn

    - name: Instalando dependências do Yarn
      run: yarn

    - name: Executa testes E2E
      run: yarn run tests

    - name: Install Allure CLI
      run: npm install -g allure-commandline

    - name: Generate Allure Report
      run: |
        npm run allure:repo

    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
